Fixes #37982 - Fix error when importing templates with `-v`
Through testing I found that `template['validation_errors']` is
apparently nil instead of an empty array when using the `-v` flag, so
the condition needs adjusting.

Below is the tested command pair with results (before the fix):
```
\# hammer -v import-templates \
--repo="https://github.com/theforeman/community-templates.git" \
--organization-ids="36" --branch="develop" \
--dirname="/partition_tables_templates/" \
--filter="FreeBSD default fake"

Could not import: Error: undefined method `empty?' for nil:NilClass

\# hammer import-templates \
--repo="https://github.com/theforeman/community-templates.git" \
--organization-ids="36" --branch="develop" \
--dirname="/partition_tables_templates/" \
--filter="FreeBSD default fake"

Import finished.
```